// contactIndex.js — the local mirror of GHL contacts that client lookup reads.
//
// GHL stays the source of truth. This is a read model: a copy shaped for
// searching, because the store that owns data is rarely the store that
// searches it well. GHL's contact search matches ordered word prefixes, is
// rejected below 3 characters, and intermittently hangs for 18-20 seconds —
// none of which a type-ahead can live with.
//
// FRESHNESS, in order of how a client actually appears:
//   1. The desk creates them  -> writeThrough() in the same request. No lag.
//   2. GHL fires a webhook    -> upsertFromWebhook(). Seconds.
//   3. Neither happened yet   -> the search falls back to GHL on a miss,
//      which is exactly the shape of "created moments ago".
//
// STALENESS is the real risk, and this codebase has paid for it before: the
// appointments cache kept blocks GHL had deleted a month earlier and one of
// them hid a live booking from the desk. So deletes are honoured and
// reconcileLocation() removes rows GHL no longer has. A row that shouldn't
// exist is worse than a row that's missing, because the desk believes it.

const { supabase } = require("../clients/supabaseClient");

const TABLE = "frontdesk_contacts";

/** Map a GHL contact into our row shape. `search_text` is generated by
    Postgres from these columns and must never be written here. */
function toRow(c, locationId) {
  if (!c?.id) return null;
  return {
    id: c.id,
    location_id: locationId,
    contact_name:
      c.contactName || `${c.firstName || ""} ${c.lastName || ""}`.trim() || null,
    first_name: c.firstName || null,
    last_name: c.lastName || null,
    email: c.email || null,
    phone: c.phone || null,
    assigned_to: c.assignedTo || null,
    // The iOS picker filters on "assigned to me OR I follow them", so the
    // follower half has to be mirrored too or artists quietly stop seeing
    // clients they follow but were never assigned.
    followers: Array.isArray(c.followers) ? c.followers : [],
    tags: Array.isArray(c.tags) ? c.tags : [],
    ghl_updated_at: c.dateUpdated || c.dateAdded || null,
    synced_at: new Date().toISOString(),
  };
}

/** Upsert a batch. Chunked because a backfill sends thousands. */
async function upsertContacts(contacts, locationId) {
  const rows = dedupeById(contacts.map((c) => toRow(c, locationId)).filter(Boolean));
  if (!rows.length) return 0;
  let written = 0;
  for (let i = 0; i < rows.length; i += 500) {
    const chunk = rows.slice(i, i + 500);
    const { error } = await supabase.from(TABLE).upsert(chunk, { onConflict: "id" });
    if (error) throw new Error(`contactIndex upsert: ${error.message}`);
    written += chunk.length;
  }
  return written;
}

/**
 * Collapse repeated ids, keeping the LAST occurrence.
 *
 * Postgres rejects an INSERT ... ON CONFLICT DO UPDATE that touches the same
 * row twice ("cannot affect row a second time"), and that error aborts the
 * whole statement — so one duplicate id anywhere in a 500-row chunk throws
 * away the chunk, the rest of the upsert, and the delete pass behind it. GHL
 * hands us duplicates routinely: paging a list that is being edited underneath
 * us will show the same contact on two pages. Seen live 2026-09-16 15:21.
 *
 * Last wins because later pages are read later, so they carry the newer copy.
 */
function dedupeById(rows) {
  const byId = new Map();
  for (const r of rows) byId.set(r.id, r);
  return [...byId.values()];
}

/**
 * Write a contact we just created ourselves. The desk booking a walk-in
 * shouldn't have to wait on a webhook round trip to be able to find them
 * again ten seconds later.
 */
async function writeThrough(contact, locationId) {
  try {
    await upsertContacts([contact], locationId);
  } catch (err) {
    // Never let indexing failure break a booking. The reconcile sweep will
    // pick this contact up, and the search falls back to GHL meanwhile.
    console.warn("[contactIndex] write-through failed (non-fatal):", err.message);
  }
}

/** Pull every contact for a location out of GHL, page by page. */
async function fetchAllFromGhl(sdk, locationId, { pageLimit = 100, maxPages = 200 } = {}) {
  const all = [];
  for (let page = 1; page <= maxPages; page++) {
    const r = await sdk.contacts.searchContactsAdvanced(
      { locationId, pageLimit, page },
      { timeout: 30000 }
    );
    const cs = r?.contacts || [];
    all.push(...cs);
    if (cs.length < pageLimit) break;
    // GHL caps deep paging; stop if we've collected the reported total.
    if (r?.total && all.length >= r.total) break;
  }
  return all;
}

/**
 * Rebuild/refresh one location, then DELETE the rows GHL didn't return.
 *
 * The delete is the whole point. An upsert-only sync looks healthy forever
 * while quietly accumulating clients who were deleted or merged away — the
 * exact failure that put a month-old phantom block on the schedule.
 *
 * It is fail-CLOSED: a partial fetch must never be read as "everything else
 * is gone". If GHL returns implausibly little compared to what we hold, the
 * sweep refuses to delete and says so.
 */
async function reconcileLocation({ sdk, locationId, dryRun = false }) {
  const started = Date.now();
  const live = await fetchAllFromGhl(sdk, locationId);
  const liveIds = new Set(live.map((c) => c.id).filter(Boolean));

  // One read serves both halves: deciding what changed, and deciding what is
  // gone. It has to be paginated — see fetchHeldRows.
  const heldRows = await fetchHeldRows(locationId);
  const held = heldRows.length;
  const heldById = new Map(heldRows.map((r) => [r.id, r]));

  // Guard: if the fetch came back far smaller than what we already hold, it
  // is far likelier that GHL paged badly than that most clients vanished.
  const suspicious = held > 100 && liveIds.size < held * 0.5;
  if (suspicious) {
    console.warn(
      `[contactIndex] refusing to reconcile ${locationId}: GHL returned ${liveIds.size} but we hold ${held}. Treating as a partial fetch, not a mass deletion.`
    );
    const { changed } = diffAgainstHeld(live, locationId, heldById);
    const upserted = dryRun ? 0 : await upsertContacts(changed, locationId);
    return {
      upserted,
      skipped: liveIds.size - changed.length,
      deleted: 0,
      held,
      fetched: liveIds.size,
      refusedDelete: true,
      ms: Date.now() - started,
    };
  }

  // Only write rows that actually differ. GHL returns every contact every
  // sweep, but a handful change between sweeps, and re-upserting ~9k
  // unchanged rows four times a day was the single largest chunk of this
  // service's outbound bandwidth (Render bills egress; Hobby includes 5 GB).
  // The comparison is over every mirrored column rather than ghl_updated_at
  // alone, because a change GHL declines to timestamp — a follower added, a
  // tag moved — must still land, or artists quietly stop seeing clients.
  const { changed } = diffAgainstHeld(live, locationId, heldById);
  const upserted = dryRun ? 0 : await upsertContacts(changed, locationId);

  // Anything we hold that GHL did not return is gone.
  const stale = heldRows.map((r) => r.id).filter((id) => !liveIds.has(id));

  let deleted = 0;
  if (stale.length && !dryRun) {
    for (let i = 0; i < stale.length; i += 500) {
      const chunk = stale.slice(i, i + 500);
      const { error: delErr } = await supabase.from(TABLE).delete().in("id", chunk);
      if (delErr) throw new Error(`contactIndex delete: ${delErr.message}`);
      deleted += chunk.length;
    }
  }
  return {
    upserted,
    skipped: liveIds.size - changed.length,
    deleted: dryRun ? stale.length : deleted,
    held,
    fetched: liveIds.size,
    dryRun,
    ms: Date.now() - started,
  };
}

/** The columns we mirror. `search_text` is generated; `synced_at` is bookkeeping. */
const MIRRORED_COLUMNS = [
  "id",
  "contact_name",
  "first_name",
  "last_name",
  "email",
  "phone",
  "assigned_to",
  "followers",
  "tags",
  "ghl_updated_at",
];

/**
 * Every row we hold for a location, paginated.
 *
 * PostgREST caps a response at 1000 rows and says nothing about it — no error,
 * no flag, just a short array. The previous read-back took that silently, so
 * for the barbershop (8.8k contacts) the delete pass only ever considered the
 * first 1000 and `deleted` was structurally 0. It failed in the safe
 * direction, which is why it survived: a stale row that should have been
 * removed simply stayed. Tattoo (~500) is under the cap and was always fine.
 *
 * Ordered by id so the pages tile exactly instead of drifting under writes.
 */
async function fetchHeldRows(locationId, { pageSize = 1000 } = {}) {
  const cols = MIRRORED_COLUMNS.join(", ");
  const out = [];
  for (let from = 0; ; from += pageSize) {
    const { data, error } = await supabase
      .from(TABLE)
      .select(cols)
      .eq("location_id", locationId)
      .order("id", { ascending: true })
      .range(from, from + pageSize - 1);
    if (error) throw new Error(`contactIndex read-back: ${error.message}`);
    const page = data || [];
    out.push(...page);
    if (page.length < pageSize) break;
  }
  return out;
}

/** timestamptz round-trips as a different string than GHL sent; compare instants. */
function sameInstant(a, b) {
  if (!a && !b) return true;
  if (!a || !b) return false;
  const ta = Date.parse(a);
  const tb = Date.parse(b);
  if (Number.isNaN(ta) || Number.isNaN(tb)) return String(a) === String(b);
  return ta === tb;
}

/** text[] comes back as an array; order is not meaningful to us. */
function sameSet(a, b) {
  const xa = Array.isArray(a) ? [...a].sort() : [];
  const xb = Array.isArray(b) ? [...b].sort() : [];
  return xa.length === xb.length && xa.every((v, i) => v === xb[i]);
}

/** Does the row we would write differ from the row already there? */
function rowChanged(next, prev) {
  if (!prev) return true;
  if (!sameInstant(next.ghl_updated_at, prev.ghl_updated_at)) return true;
  if (!sameSet(next.followers, prev.followers)) return true;
  if (!sameSet(next.tags, prev.tags)) return true;
  for (const k of ["contact_name", "first_name", "last_name", "email", "phone", "assigned_to"]) {
    if ((next[k] ?? null) !== (prev[k] ?? null)) return true;
  }
  return false;
}

/** Split GHL's contacts into the ones worth writing. Returns GHL-shaped contacts. */
function diffAgainstHeld(live, locationId, heldById) {
  const changed = [];
  for (const c of live) {
    const next = toRow(c, locationId);
    if (!next) continue;
    if (rowChanged(next, heldById.get(next.id))) changed.push(c);
  }
  return { changed };
}

/** A contact webhook told us something changed. */
async function upsertFromWebhook(payload) {
  const c = payload?.contact || payload;
  const locationId = payload?.locationId || c?.locationId;
  if (!c?.id || !locationId) return false;
  await upsertContacts([c], locationId);
  return true;
}

/** A contact webhook told us one is gone. Honour it immediately. */
async function deleteFromWebhook(payload) {
  const c = payload?.contact || payload;
  const id = c?.id;
  if (!id) return false;
  const { error } = await supabase.from(TABLE).delete().eq("id", id);
  if (error) throw new Error(`contactIndex webhook delete: ${error.message}`);
  return true;
}

/**
 * Search the index.
 *
 * Every token must appear somewhere in `search_text` — an AND of unanchored
 * LIKEs, which the trigram index serves. Word order, mid-word fragments and
 * phone suffixes all fall out of that for free, because `search_text` is
 * name + email + bare digits in one normalised string.
 *
 * Returns GHL-shaped contacts so callers can treat index and API results
 * identically.
 */
async function searchIndex({ locationId, tokens, limit = 200, assignedTo = null }) {
  if (!tokens.length) return [];
  let q = supabase.from(TABLE).select("*").eq("location_id", locationId);
  if (assignedTo) {
    // Assigned to them, or followed by them — the same predicate the iOS
    // picker sent to GHL.
    q = q.or(`assigned_to.eq.${assignedTo},followers.cs.{${assignedTo}}`);
  }
  for (const t of tokens) {
    // ilike with %...% — the GIN trigram index makes this a real index scan
    // rather than the sequential scan it would be on a btree.
    q = q.ilike("search_text", `%${t.replace(/[%_]/g, "")}%`);
  }
  const { data, error } = await q.limit(limit);
  if (error) throw new Error(`contactIndex search: ${error.message}`);
  return (data || []).map((r) => ({
    id: r.id,
    contactName: r.contact_name,
    firstName: r.first_name,
    lastName: r.last_name,
    email: r.email,
    phone: r.phone,
    assignedTo: r.assigned_to,
    followers: r.followers || [],
    tags: r.tags || [],
  }));
}

/**
 * Trigram word-similarity search, for when exact and substring matching have
 * both found nothing. This is the only pass that can survive a typo in the
 * FIRST characters of a name — a stem taken off the front of a misspelling is
 * itself misspelled, so "Mlikert" can never stem its way to Milkert.
 */
async function fuzzyIndex({ locationId, q, minSim = 0.3, maxRows = 50 }) {
  const { data, error } = await supabase.rpc("search_contacts_fuzzy", {
    loc: locationId,
    q,
    min_sim: minSim,
    max_rows: maxRows,
  });
  if (error) throw new Error(`contactIndex fuzzy: ${error.message}`);
  return (data || []).map((r) => ({
    id: r.id,
    contactName: r.contact_name,
    firstName: r.first_name,
    lastName: r.last_name,
    email: r.email,
    phone: r.phone,
    assignedTo: r.assigned_to,
    followers: r.followers || [],
    tags: r.tags || [],
  }));
}

/** How many contacts we hold for a location (for the "showing N of M" line). */
async function countIndex({ locationId, tokens, assignedTo = null }) {
  let q = supabase
    .from(TABLE)
    .select("*", { count: "exact", head: true })
    .eq("location_id", locationId);
  if (assignedTo) {
    q = q.or(`assigned_to.eq.${assignedTo},followers.cs.{${assignedTo}}`);
  }
  for (const t of tokens) q = q.ilike("search_text", `%${t.replace(/[%_]/g, "")}%`);
  const { count, error } = await q;
  if (error) return null;
  return count ?? null;
}

module.exports = {
  TABLE,
  toRow,
  upsertContacts,
  dedupeById,
  writeThrough,
  fetchAllFromGhl,
  fetchHeldRows,
  rowChanged,
  reconcileLocation,
  upsertFromWebhook,
  deleteFromWebhook,
  searchIndex,
  fuzzyIndex,
  countIndex,
};
