// contactIndex.js — the local mirror of GHL contacts that client lookup reads.
//
// GHL stays the source of truth. This is a read model: a copy shaped for
// searching, because the store that owns data is rarely the store that
// searches it well. GHL's contact search matches ordered word prefixes, is
// rejected below 3 characters, and intermittently hangs for 18-20 seconds —
// none of which a type-ahead can live with.
//
// FRESHNESS, in order of how a client actually appears:
//   1. The desk creates them  -> writeThrough() in the same request. No lag.
//   2. GHL fires a webhook    -> upsertFromWebhook(). Seconds.
//   3. Neither happened yet   -> the search falls back to GHL on a miss,
//      which is exactly the shape of "created moments ago".
//
// STALENESS is the real risk, and this codebase has paid for it before: the
// appointments cache kept blocks GHL had deleted a month earlier and one of
// them hid a live booking from the desk. So deletes are honoured and
// reconcileLocation() removes rows GHL no longer has. A row that shouldn't
// exist is worse than a row that's missing, because the desk believes it.

const { supabase } = require("../clients/supabaseClient");

const TABLE = "frontdesk_contacts";

/** Map a GHL contact into our row shape. `search_text` is generated by
    Postgres from these columns and must never be written here. */
function toRow(c, locationId) {
  if (!c?.id) return null;
  return {
    id: c.id,
    location_id: locationId,
    contact_name:
      c.contactName || `${c.firstName || ""} ${c.lastName || ""}`.trim() || null,
    first_name: c.firstName || null,
    last_name: c.lastName || null,
    email: c.email || null,
    phone: c.phone || null,
    assigned_to: c.assignedTo || null,
    tags: Array.isArray(c.tags) ? c.tags : [],
    ghl_updated_at: c.dateUpdated || c.dateAdded || null,
    synced_at: new Date().toISOString(),
  };
}

/** Upsert a batch. Chunked because a backfill sends thousands. */
async function upsertContacts(contacts, locationId) {
  const rows = contacts.map((c) => toRow(c, locationId)).filter(Boolean);
  if (!rows.length) return 0;
  let written = 0;
  for (let i = 0; i < rows.length; i += 500) {
    const chunk = rows.slice(i, i + 500);
    const { error } = await supabase.from(TABLE).upsert(chunk, { onConflict: "id" });
    if (error) throw new Error(`contactIndex upsert: ${error.message}`);
    written += chunk.length;
  }
  return written;
}

/**
 * Write a contact we just created ourselves. The desk booking a walk-in
 * shouldn't have to wait on a webhook round trip to be able to find them
 * again ten seconds later.
 */
async function writeThrough(contact, locationId) {
  try {
    await upsertContacts([contact], locationId);
  } catch (err) {
    // Never let indexing failure break a booking. The reconcile sweep will
    // pick this contact up, and the search falls back to GHL meanwhile.
    console.warn("[contactIndex] write-through failed (non-fatal):", err.message);
  }
}

/** Pull every contact for a location out of GHL, page by page. */
async function fetchAllFromGhl(sdk, locationId, { pageLimit = 100, maxPages = 200 } = {}) {
  const all = [];
  for (let page = 1; page <= maxPages; page++) {
    const r = await sdk.contacts.searchContactsAdvanced(
      { locationId, pageLimit, page },
      { timeout: 30000 }
    );
    const cs = r?.contacts || [];
    all.push(...cs);
    if (cs.length < pageLimit) break;
    // GHL caps deep paging; stop if we've collected the reported total.
    if (r?.total && all.length >= r.total) break;
  }
  return all;
}

/**
 * Rebuild/refresh one location, then DELETE the rows GHL didn't return.
 *
 * The delete is the whole point. An upsert-only sync looks healthy forever
 * while quietly accumulating clients who were deleted or merged away — the
 * exact failure that put a month-old phantom block on the schedule.
 *
 * It is fail-CLOSED: a partial fetch must never be read as "everything else
 * is gone". If GHL returns implausibly little compared to what we hold, the
 * sweep refuses to delete and says so.
 */
async function reconcileLocation({ sdk, locationId, dryRun = false }) {
  const started = Date.now();
  const live = await fetchAllFromGhl(sdk, locationId);
  const liveIds = new Set(live.map((c) => c.id).filter(Boolean));

  const { count: heldBefore } = await supabase
    .from(TABLE)
    .select("*", { count: "exact", head: true })
    .eq("location_id", locationId);

  // Guard: if the fetch came back far smaller than what we already hold, it
  // is far likelier that GHL paged badly than that most clients vanished.
  const held = heldBefore || 0;
  const suspicious = held > 100 && liveIds.size < held * 0.5;
  if (suspicious) {
    console.warn(
      `[contactIndex] refusing to reconcile ${locationId}: GHL returned ${liveIds.size} but we hold ${held}. Treating as a partial fetch, not a mass deletion.`
    );
    const upserted = await upsertContacts(live, locationId);
    return { upserted, deleted: 0, held, fetched: liveIds.size, refusedDelete: true, ms: Date.now() - started };
  }

  const upserted = dryRun ? 0 : await upsertContacts(live, locationId);

  // Anything we hold that GHL did not return is gone.
  const { data: ours, error } = await supabase
    .from(TABLE)
    .select("id")
    .eq("location_id", locationId);
  if (error) throw new Error(`contactIndex read-back: ${error.message}`);
  const stale = (ours || []).map((r) => r.id).filter((id) => !liveIds.has(id));

  let deleted = 0;
  if (stale.length && !dryRun) {
    for (let i = 0; i < stale.length; i += 500) {
      const chunk = stale.slice(i, i + 500);
      const { error: delErr } = await supabase.from(TABLE).delete().in("id", chunk);
      if (delErr) throw new Error(`contactIndex delete: ${delErr.message}`);
      deleted += chunk.length;
    }
  }
  return {
    upserted,
    deleted: dryRun ? stale.length : deleted,
    held,
    fetched: liveIds.size,
    dryRun,
    ms: Date.now() - started,
  };
}

/** A contact webhook told us something changed. */
async function upsertFromWebhook(payload) {
  const c = payload?.contact || payload;
  const locationId = payload?.locationId || c?.locationId;
  if (!c?.id || !locationId) return false;
  await upsertContacts([c], locationId);
  return true;
}

/** A contact webhook told us one is gone. Honour it immediately. */
async function deleteFromWebhook(payload) {
  const c = payload?.contact || payload;
  const id = c?.id;
  if (!id) return false;
  const { error } = await supabase.from(TABLE).delete().eq("id", id);
  if (error) throw new Error(`contactIndex webhook delete: ${error.message}`);
  return true;
}

/**
 * Search the index.
 *
 * Every token must appear somewhere in `search_text` — an AND of unanchored
 * LIKEs, which the trigram index serves. Word order, mid-word fragments and
 * phone suffixes all fall out of that for free, because `search_text` is
 * name + email + bare digits in one normalised string.
 *
 * Returns GHL-shaped contacts so callers can treat index and API results
 * identically.
 */
async function searchIndex({ locationId, tokens, limit = 200 }) {
  if (!tokens.length) return [];
  let q = supabase.from(TABLE).select("*").eq("location_id", locationId);
  for (const t of tokens) {
    // ilike with %...% — the GIN trigram index makes this a real index scan
    // rather than the sequential scan it would be on a btree.
    q = q.ilike("search_text", `%${t.replace(/[%_]/g, "")}%`);
  }
  const { data, error } = await q.limit(limit);
  if (error) throw new Error(`contactIndex search: ${error.message}`);
  return (data || []).map((r) => ({
    id: r.id,
    contactName: r.contact_name,
    firstName: r.first_name,
    lastName: r.last_name,
    email: r.email,
    phone: r.phone,
    assignedTo: r.assigned_to,
    tags: r.tags || [],
  }));
}

/**
 * Trigram word-similarity search, for when exact and substring matching have
 * both found nothing. This is the only pass that can survive a typo in the
 * FIRST characters of a name — a stem taken off the front of a misspelling is
 * itself misspelled, so "Mlikert" can never stem its way to Milkert.
 */
async function fuzzyIndex({ locationId, q, minSim = 0.3, maxRows = 50 }) {
  const { data, error } = await supabase.rpc("search_contacts_fuzzy", {
    loc: locationId,
    q,
    min_sim: minSim,
    max_rows: maxRows,
  });
  if (error) throw new Error(`contactIndex fuzzy: ${error.message}`);
  return (data || []).map((r) => ({
    id: r.id,
    contactName: r.contact_name,
    firstName: r.first_name,
    lastName: r.last_name,
    email: r.email,
    phone: r.phone,
    assignedTo: r.assigned_to,
    tags: r.tags || [],
  }));
}

/** How many contacts we hold for a location (for the "showing N of M" line). */
async function countIndex({ locationId, tokens }) {
  let q = supabase
    .from(TABLE)
    .select("*", { count: "exact", head: true })
    .eq("location_id", locationId);
  for (const t of tokens) q = q.ilike("search_text", `%${t.replace(/[%_]/g, "")}%`);
  const { count, error } = await q;
  if (error) return null;
  return count ?? null;
}

module.exports = {
  TABLE,
  toRow,
  upsertContacts,
  writeThrough,
  fetchAllFromGhl,
  reconcileLocation,
  upsertFromWebhook,
  deleteFromWebhook,
  searchIndex,
  fuzzyIndex,
  countIndex,
};
